replicaCount: 1

image:
  repository: docker.io/matmechdocker/matmech-bgd
  pullPolicy: IfNotPresent
  tag: 1.0.1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}
